version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres

    restart: always

    environment:
      POSTGRES_DB: fault_find_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DB/imports:/imports

  backend:

    env_file:
      - .env

    build:
      context: ./faultFind_backend

    container_name: backend

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fault_find_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:

    build:
      context: ./faultFind_frontend

    container_name: frontend

    depends_on:
      - backend

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro

volumes:
  postgres_data:
