spring:
  application:
    # 애플리케이션 이름
    name: fault_find_backend

  datasource:
    # PostgreSQL JDBC 드라이버
    driver-class-name: org.postgresql.Driver

    # PostgreSQL 접속 주소
    url: jdbc:postgresql://localhost:5432/fault_find_db

    # 환경변수 DB_USER가 없으면 postgres 사용
    username: ${DB_USER:postgres}

    # 환경변수 DB_PW가 없으면 1111 사용
    password: ${DB_PW:1111}

  jpa:
    hibernate:
      # Entity 변경사항을 기반으로 테이블 자동 생성/수정
      # 개발 단계에서 사용
      ddl-auto: update

    properties:
      hibernate:
        # 실행되는 SQL 출력
        show_sql: true

        # SQL 포맷팅
        format_sql: true

  autoconfigure:
    exclude:
      # Spring Security 자동 설정 비활성화
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    access-expiration: 3600000
logging:
  level:
    # SQL 파라미터 바인딩 값 출력
    org.hibernate.orm.jdbc.bind: trace