spring:
  application:
    name: fault_find_backend

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  forward-headers-strategy: framework